### PR TITLE
Docker tools rewrite

### PR DESCRIPTION
**Pull request by bjones1**
WIP -- adding the `--multi` option, other fixes. Still broken, need work...

### CODE REVIEW

**Comment by bjones1** [comment]
I just rebased this onto master and fixed a few more things. It's still broken, though. It looks like the new version of Poetry (1.1.12) released 2 days ago causes problems -- I'd recommend using Poetry 1.1.11 for now (need to update the Poetry install in several places in `docker_tools.py`).

**Comment by bjones1** [comment]
Currently, the necessary env vars aren't being passed to the bookserver, so it's using the wrong directory for books. Not sure why this changed...

**Comment by bnmnetp** [comment]
I am getting a `ModuleNotFoundError: No module named 'bookserver'` error.

This seems to be due to the fact that `bookserver` is kind of installed and kind of not.

in the site-packages folder there is a bookserver.pth file that references /srv/BookServer

The pyproject.toml file appears correct. as does the lock file.

shelling in to the container and `pip uninstall bookserver` followed by `pip install bookserver` gets me to the same place you probably were.

```
File "/srv/web2py/applications/runestone/.venv/lib/python3.8/site-packages/starlette/routing.py", line 540, in lifespan
runestoneserver-runestone-1  |     async for item in self.lifespan_context(app):
runestoneserver-runestone-1  |   File "/srv/web2py/applications/runestone/.venv/lib/python3.8/site-packages/starlette/routing.py", line 481, in default_lifespan
runestoneserver-runestone-1  |     await self.startup()
runestoneserver-runestone-1  |   File "/srv/web2py/applications/runestone/.venv/lib/python3.8/site-packages/starlette/routing.py", line 516, in startup
runestoneserver-runestone-1  |     await handler()
runestoneserver-runestone-1  |   File "/srv/web2py/applications/runestone/.venv/lib/python3.8/site-packages/bookserver/main.py", line 72, in startup
runestoneserver-runestone-1  |     os.makedirs(settings.book_path, exist_ok=True)
runestoneserver-runestone-1  |   File "/usr/local/lib/python3.8/os.py", line 213, in makedirs
runestoneserver-runestone-1  |     makedirs(head, exist_ok=exist_ok)
runestoneserver-runestone-1  |   File "/usr/local/lib/python3.8/os.py", line 223, in makedirs
runestoneserver-runestone-1  |     mkdir(name, mode)
runestoneserver-runestone-1  | PermissionError: [Errno 13] Permission denied: '/root/Runestone'
```
Not sure how to fix that other than removing poetry.lock before we build.


So, I have a working server now...   I'm not sure what to change, but I'm going to tell you what I did manually and I hope this will either give you enough to change or enough to tell me what to change.

I had to shell into the container and using pip, uninstall both `bookserver` and  `runestone`. I then ran `pip install --pre runestone=="6.0.0dev"` You need the `--pre` in order to install a prerelease. which `6.0.0dev` is due to the `dev` after the last 0. Maybe you knew that.

I also made a new release of bookserver `0.3.9` which included some recent merges from you. Probably important! 😬

**Comment by bnmnetp** [comment]
I just did a new build and all seems to be fine!  Other than removing `poetry.lock` the only change I made was to the `pyproject.toml` file for Runestone.

```
runestone = {version = "^6.0.0*", allow-prereleases = true }
```
The current line for `bookserver` **must** install at least `0.3.9` 

I **wish** poetry **would be** much more aggressive about allowing pyproject.toml to boss poetry.lock.  My understanding/intuition/experience is to not edit poetry.lock by hand, but when pyproject.toml and poetry.lock differ it is often hard to reconcile without simply removing poetry.lock and letting poetry figure it out.  So perhaps, for the short term, that is our best strategy?

**Comment by bnmnetp** [comment]
Also... my merge and other stuff is on the `bjones-docker-tools-rewrite` branch in my repo.

**Comment by bjones1** [comment]
Running `poetry update` should update the `poetry.lock` file. You can also `poetry update --lock` just to update the file, but not to install anything.

**Pull request merged**
