### PR TITLE
Make base course search criteria for q bank

### PR DESCRIPTION
**Pull request by millro04**
This should fix issue 773.

### CODE REVIEW

**Comment by bnmnetp** [comment]
OK, that looks fine.   Now, we could make it MUCH easier if we made the chapter a dropdown.  I think you could do this very easily because now that you know the base_course you can select the chapter labels with a simple select like this one:

```
select chapter_label from chapters where course_id = 'thinkcspy';
```

Can you add that to this PR?

**Comment by millro04** [comment]
Yep, will course_id be 'thinkcspy' or the integer id corresponding to the course?

**Comment by bnmnetp** [comment]
course_id is a string just like in the example

**Comment by millro04** [comment]
Ok, see if that works. I didn't have any chapters in my table so I just made up a few for testing purposes, but I think it should work.

**Comment by millro04** [comment]
This last commit makes the default option for the select to be nothing, that way we aren't forcing them to pick one of the chapters in the search if they don't want to search for that.

**Pull request merged**
