### PR TITLE
Slight restructuring; wording changes

### PR DESCRIPTION
**Pull request by debbieyuster**

### CODE REVIEW

**Comment by bjones1** [comment]
Debbie, thanks for these improvements! I appreciate the careful editing. Have you been able to render these edits to HTML? I think I see a few minor errors in that regard. I'll be happy to guide you through that process if you're not familiar with it.

**Comment by debbieyuster** [comment]
Thanks @bjones1, I previewed the edits before submitting but could only see a kind of diff'ed view of the rendered markdown. I'm not sure how to view the rendered HTML, I'd appreciate any guidance.

**Comment by debbieyuster** [comment]
Ok I've updated the PR - I believe it should render fine now.

**Comment by bjones1** [comment]
Looks great to me! Thanks!

**Pull request merged**
