### PR TITLE
Add: Server-side tests of fitb.

### PR DESCRIPTION
**Pull request by bjones1**
This is a simple PR that adds much more testing for the server-side fill-in-the-blanks question type. The tests demonstrate that grading works properly on the server.

### CODE REVIEW

**Comment by bjones1** [comment]
Tests fail since they're running against the currently released version of RunestoneComponents, not the current Github version. @bnmnetp, what do you think about changing the test suite to use the Github version of RunestoneComponents instead?

**Comment by bnmnetp** [comment]
@bjones1 using the github version is probably better as we so often are doing development that requires changes on both sides.

**Comment by bjones1** [comment]
Sounds good. I'll create a separate PR for that, then rebase this on top of it.

**Comment by bjones1** [comment]
I just included it here, since the two go together. This is ready to merge.

**Comment by bjones1** [comment]
Thanks!

**Pull request merged**
