### PR TITLE
Misc cleanup

### PR DESCRIPTION
**Pull request by bjones1**
A set of tweaks and cleanup to the tests.

### CODE REVIEW

**Comment by bnmnetp** [comment]
If we are removing the start script then you need to update the README with new instructions for how to start a server.

**Comment by bjones1** [comment]
I'm mainly removing this since it's outdated -- it tries to start the scheduler, which has been used only by me (AFAIK) ever since we moved to dynamic books. Would you recommend just editing the script instead? Does anyone actually use this?

**Comment by bjones1** [comment]
For simplicity, I just removed the portion of that script that started the scheduler, but left the rest intact.

**Comment by bnmnetp** [comment]
Thats good.  Thanks.

**Pull request merged**
