### PR TITLE
Fix: Provide an error report when the assignment table raises an exception

### PR DESCRIPTION
**Pull request by bjones1**
Better error reporting per #1470.

### CODE REVIEW

**Comment by bjones1** [comment]
I just pushed an update with a fix for my guess at what's wrong. Let me know when you're available to test on your server.

**Comment by bjones1** [comment]
Perhaps +1 for unit tests again. I created a unit test for the case I think my code missed, verified that the tests fails (with the same sort of exception as you saw), then verified the new code makes it pass. Let me know if this works.

**Comment by bnmnetp** [comment]
Yikes, this seemed to help on my dev machine, but on the live machine it is bringing Postgres to its knees!

**Comment by bjones1** [comment]
Oh no! I've used some nice tools to look at postgres performannce -- let me know if you want help/info on those. There's some comments on them in `questions_report.py`. (I needed these for another type query, not for what we're using right now.)

**Comment by bnmnetp** [comment]
I just reverted this merge as the query seems to run whenever you select an assignment on the grading page.  

The query starts and that cpu goes immediately to 100% for Postgres.  I had all of the cpus on academy pegged at 100% until I could manually kill off these queries, some of which were running for more than 10 minutes.

**Comment by bjones1** [comment]
Holy indexes, batman! Let me know how I can help...

**Comment by bnmnetp** [comment]
Not even sure where to start... DISTINCT is always a warning flag for performance.  Unfortunately I don't really have a lot of time for this right now, as the exam generator project has to be my top priority.  It would be nice to at least get the js error handling live so people are not left wondering.

**Comment by bjones1** [comment]
The first commit in this PR fixes that. Do you want that as a separate PR? I might also work on an alternative approach and see if that helps.

**Pull request merged**
