### PR TITLE
Working on making parsons and fill in the blank autogradeable for #924

### PR DESCRIPTION
**Pull request by gardhi01**

### CODE REVIEW

**Comment by gardhi01** [comment]
Sorry about all the indentation changes--Sublime was formatting things strangely, so whenever I would add lines of code, I ran into indentation errors.
The helper function bit is there at Paul's request.

**Comment by bnmnetp** [comment]
You need to tell sublime to indent by 4 spaces

**Comment by gardhi01** [comment]
The autograder looks for first_answer and last_answer in autograde_one_q (around line 539). That's something that Paul already implemented. The elif statements that I added in autograde_one_q just collect all the answers that a particular student gave for a particular question and determine the scoring function.  Then the answer to be scored is determined by Paul's first_answer last_answer conditional.

**Comment by bnmnetp** [comment]
OK, so....  the following should be autogradeable.  You can check off the one's that are complete.

- [ ] multiple choice
- [ ] activecode  -- using unit tests both all or nothing or a percentage of tests passed
- [ ] clickableArea
- [ ] dragndrop
- [ ] fill in the blank
- [ ] parsons
- [ ] usage -- @presnick may have this completed??
- [ ] codelens questions

**Comment by gardhi01** [comment]
I'm not seeing clickableArea or dragndrop in the question_type column of the questions table. Where would I find those types of questions?

**Comment by bnmnetp** [comment]
There is a database table for dragndrop_answers and clickablearea_answers just like the others.

They are newer and not as widely used in the textbooks yet.  And maybe there is missing code in their implementation that they are not adding themselves to the questions table like they should.

I'll investigate that side.

**Comment by gardhi01** [comment]
Okay, I'll try to create my own questions and see how that affects things.

One other question I have is about the codelens questions.  I saw that Bryan said they could provide a correct answer, but codelens doesn't have its own answers table in the database. Would we want to create a codelens_answers table?

**Comment by bnmnetp** [comment]
You can also clone the RunestoneInteractive/overview  and build that.  It has examples of both.

I think we do want to add a codlens answers table.

**Comment by gardhi01** [comment]
What does the minheight column in the dragndrop_answers keep track of?

**Comment by gardhi01** [comment]
I am slightly confused by codelens questions. I've looked at several, but there doesn't seem to be a way for a student to alter the code in any way--the only way a student can interact with the codelens question is by stepping through the provided code with the buttons or using the slider. How can a student be correct or incorrect with a codelens question?  Or is codelens one of those question types that should just be graded on a student's interactivity?

**Comment by bnmnetp** [comment]
If you look at the overview you will see that there is an option to ADD questions to codelens so that when the student is stepping through the code it will pop up a modal and ask the student to predict either the value of a variable at that point, or what the next line to be executed will be.

**Comment by bnmnetp** [comment]
The assignment pages are looking good @gardhi01 !

I've pulled everything onto the assignment_interface branch.  This includes the latest from Bryan and Paul for doing the readings part of the assignment.  So perhaps you could pull that branch to see how the readings are stored and add them to the assignment page too.??

**Comment by gardhi01** [comment]
@bnmnetp The last commit I made will allow scripts inside the rendered html to run. This will let codelens questions render correctly within the dynamic assignment pages, but I'm worried it may be a bit of a security risk. What are your thoughts?

**Pull request merged**
