### PR TITLE
Add: A basic Selenium test.

### PR DESCRIPTION
**Pull request by bjones1**
This paves to way for lots of good JS in broswer/server-side interaction tests.

### CODE REVIEW

**Comment by bjones1** [comment]
OK, this is finally ready to go.

Note that it's not integrated into Docker. As I know less of Docker, I haven't tried this piece.

**Comment by bnmnetp** [comment]
This needs to at least not break docker.  Docker is a full citizen of our ecosystem that a several projects I know of rely on.  I do all my development and run all of my unit tests on a docker setup.

Do you think it is mainly that we need to add key components to the docker setup, such as selenium itself and the chromedriver?

**Comment by bjones1** [comment]
Yes, that's all. Basically, just reflect the changes in `.travis.yml` to Docker-ese.

**Comment by bjones1** [comment]
OK, here's my attempt at Docker. However, I still can't get Chrome to run in a container (on xvfb, of course). Any help is appreciated.

**Comment by bjones1** [comment]
OK, this works on Docker now. That was painful.

**Comment by bjones1** [comment]
Pinging on this...

**Pull request merged**
