### PR TITLE
Add: question reports

### PR DESCRIPTION
**Pull request by bjones1**
I think the code to produce an Excel report of an assignment is actually pretty neat. But, it needs a GUI (pick an assignment), plus it doesn't cover all question types.

There's also code for team evals, but ignore it for now -- I'll clean it up and work on that piece later.

### CODE REVIEW

**Comment by bjones1** [comment]
I've done a pretty significant refactor/rewrite. This now contains only code for querying students' responses to questions, and an Excel report generator.

At its heart is a IMHO nifty set of queries which efficiently extracts info about a set of questions in a given class: for each student and each problem, the answer, timestamp, correctness, grade, and number of attempts. Since the database does most of the work, the query is very efficient -- < 2 s for a class of 180 students with 20+ questions per student.

This is a lot of valuable info. It could be used to power an improved autograder, a better grading interface, and much more. Currently, I use this data to produce a nice Excel spreadsheet of the data. However, I'm hoping other can take this as a starting point for something wonderful!

Unfinished tasks:
- [ ] Provide a UI for the endpoint. Currently, it must be accessed manually as `runestone/assignments/grades_report?assignment=xxx`, where `xxx` is the name of an assignment.
- [ ] Support more question types. Currently, I support fill-in-the-blank, multiple choice, short answer, and literate programming questions. Adding more is easy -- see https://github.com/RunestoneInteractive/RunestoneServer/pull/1266/files#diff-c3b101f31e681ddfb1dd5fb4b5dc4cfbR181.
- [ ] Use this for a next-gen something (autograder, grading interface, etc.).

**Comment by bjones1** [comment]
OK, this is finally fixed (test pass) and ready to merge.

**Comment by bjones1** [comment]
Brad, pinging on this. It's ready IMHO and still a good addition, even if more work can be done to enhance/improve this.

**Comment by bnmnetp** [comment]
Sorry, I was on vacation for 10 days, and have been giving other things priority.

1.  I don't see how to get to this report.
2. I think we should talk to a bunch of people and decide what we want.  It feels like kind of a mishmash of different kinds/styles of reports.  We have the student progress tab (which is where i expected to find  a link to this) . On that tab we have things that can be viewed online or downloaded as CSV files.  Then we have this, which cannot be viewed online but can be downloaded as an Excel file.  We have some things that are done with d3 we have other things done with Pandas...  

I would really like to see a more unified approach before we make it even harder on ourselves.

**Comment by bnmnetp** [comment]
OK, I finally looked back far enough to see the URL to use.  This seems substantially the same (although focused on an assignment) as the Overview Reports that you can access from the Student Progress tab.

**Comment by bjones1** [comment]
Thanks for taking a look. I hadn't looked closely at the student reports. I see that, for a given problem, the information is fairly similar. I agree that we need some coherence in all the reports that Runestone produces. That sounds like a good discussion topic for the next dev meeting. Quickly listing what I'm aware of:

1. The instructor interface/grading tab allow access to see each student's answer for a given problem, and to view/edit their grade. This is available only for instructors.
2. The student progress tab shows a variety of info: summary info on all pages in a chapter (the links are broken for me) under "Overall Progression", class activity under "Class Activity", and donut charts for each question under "Exercise analytics" with a very nice report on a per-exercise link. However, since the chapter/subchapter/page/question info isn't provided for an exercise, I find this rather hard to use. Plus, the backend that produces this data needs a giant overhaul, from what I understand.
3. The overview reports, accessible from the student progress tab, seem fairly broken -- I get lots of "Nan" entries, and only a few students in my class show up in the report.
4. The gradebook, accessible from a button in the student progress tab,  produces a nice report, but the horizontal scrolling is almost unusable. Each grade is clickable, which produces a nice detailed report for that student.
5. Where's your pandas report? I don't remember where it ended up.

We should think about what data to present, how to present it, and how to query it more efficiently. My quick thoughts:

- There will be two basic views: overview by either chapters or assignments, and a detail view of each chapter/assignment:
- The overview: present all data in a table, where the rows are students and columns are either chapter/subchapters or assignments. This would be much like the existing gradebook, and a re-presentation of the existing "Overall progression". Clicking on a cell would transition to the same screen as the existing reports.
- The detail view -- selecting a specific chapter or assignment changes the columns to show all questions in the given assignment/chapter. Each cell should report number of times answered, the timestamp of the last answer, the last answer, and the assigned grade. Clicking on a cell should show the question itself along with all answers/grades/timestamps for that student. Instructors could edit grades in a given cell.

These would therefore replace much of the grading tab.

**Comment by bjones1** [comment]
I'm closing this for now, to postpone discussion until we get feedback from other instructors (probably the end of the fall 2019 semester) to determine what others want.

**Pull request closed without merging**
