### PR TITLE
Add: Server-side support for literate programming question types.

### PR DESCRIPTION
**Pull request by bjones1**
This is the server side for https://github.com/RunestoneInteractive/RunestoneComponents/pull/817. It won't pass until that PR is merged.

### CODE REVIEW

**Comment by bnmnetp** [comment]
I merged #817 but I'm still getting a fail on the tests.

```
Extension error:
Could not import extension CodeChat.CodeToRestSphinx (exception: No module named 'sphinx.project')
```

**Comment by bnmnetp** [comment]
@bjones1 It appears taht sphinx.project is sphinx >= 2.0 ??

I upgraded to 2.0.1 and that error went away.

But I am seeing:

```
Running Sphinx v2.0.1
WARNING: while setting up extension runestone.lp: role 'docname' is already registered, it will be overridden
```

Is that intentional?  Seems like a bad idea to override an existing role, unless it is compatible but does more?

**Comment by bjones1** [comment]
Oops -- I didn't think about that case. Yes, CodeChat requires Sphinx 2.0.

The warning is ignorable -- the new `docname` role is a Runestone/Sphinx-customized version of the more generic `docname` role provided by CodeChat for docutils.

**Comment by bnmnetp** [comment]
Yeah, CodeChat also causes the 2.7 build/test to fail when it tries to install CodeChat

I updated the master:requirements.txt to specify sphinx>=1.8.5 which works for sphinx but CodeChat definitely breaks anything with 2.7

**Comment by bnmnetp** [comment]
Previously, the only purpose of having the scheduler running was for building books.  It looks like you have some other need for that in this PR??

**Comment by bjones1** [comment]
Hmm, CodeChat should only be installed for Python 3 -- in `requirements.txt`, it is:

`CodeChat; python_version != '2.7'`

I use the scheduler to run builds/simulations on the webhost.

**Comment by bnmnetp** [comment]
OK, good to know.  I had disabled the scheduler in Docker thinking we were through with it!  Then when I merged your PR onto my dev branch everything started crashing due to an import problem with scheduler!

**Comment by bnmnetp** [comment]
It would be great to have a small PR against the overview book that shows how this is used.

Also, if you  could add a docstring to class _LpBuildButtonDirective then the `runestone doc lp_build` command will show the documentation for it like it does for other runestone directives.

**Pull request merged**
