### PR TITLE
add student id to gradebook row

### PR DESCRIPTION
**Pull request by haugrud**
student id can facilitate import to LMS 
username is the field I wanted

### CODE REVIEW

**Comment by bnmnetp** [comment]
Crash  -- Can't add int's and str's

**Comment by haugrud** [comment]
split first and last names and add username to gradebook

**Comment by bnmnetp** [comment]
When I try this I get a crash on line 207 `average += grantable[grade][col]`  Its trying to add 0 and 'Miller'  -- maybe this is a work in progress and I should wait until you give me the green light.

**Comment by haugrud** [comment]
I was concerned about the averages. I'll see what else I can do.


Michael Haugrud
Department of Computer Science and Information Systems
Minnesota State University Moorhead
________________________________

**Comment by bnmnetp** [comment]
I just had to adjust the `item-1` to `item-3` to account for the additional two header rows.

**Pull request merged**
