### PR TITLE
Db to bookserver

### PR DESCRIPTION
**Pull request by bjones1**
Fixes (plus one DELME) to get web2py playing nicely with the bookserver.

### CODE REVIEW

**Comment by bjones1** [comment]
@bnmnetp, I'm confused -- this got marked as closed because of a merge in another repo? Is this github weirdness? This PR still definitely needs to be merged...

**Comment by bnmnetp** [comment]
It is still in my open PR list, it just needs to have a conflict resolved.

Separate but related:

I wonder if the flow that we use in entrypoint.sh for the docker container where we use the rsmanage command to check the state of the database and if necessary create all of the tables before starting EITHER server  might not give us a little more flexibility in the short/medium term than completely disabling migrations?  I only say this because I think for both of us (and others running servers) the main use case is going to be to keep the existing database and have bookserver work with it.

**Comment by bjones1** [comment]
Oops, I missed the conflict. I went ahead and merged in upstream/bookserver and pushed the change.

I agree that we need to plan for both servers running together in the short/medium term. I'll discuss with you on Slack.

**Comment by bjones1** [comment]
@bnmnetp , this is ready now. Let me know if you see any other changes you want me to make.

**Comment by bnmnetp** [comment]
Thanks @bjones1 -- Is this holding up anything for you?  I have those two changes to the schema that are part of my peer_support branch.  So I'm thinking whether I should wait on this until after that is merged or if I should just go ahead and merge this and deal with that migration when I merge that branch.

**Comment by bjones1** [comment]
This no longer has schema changes, just disables migrations for bookserver tables.

**Pull request merged**
