### PR TITLE
Add: activecode test.

### PR DESCRIPTION
**Pull request by bjones1**
This will fail until https://github.com/RunestoneInteractive/RunestoneComponents/pull/1175 is merged.

### CODE REVIEW

**Comment by bjones1** [comment]
This should pass after merging the components updates.

**Comment by bjones1** [comment]
@bnmnetp, would you re-start the tests, since the components PR is now merged?

**Comment by bnmnetp** [comment]
@bjones1 I did restart, but we are still getting timeouts in test_shortanswer and this time in testing activecode

**Comment by bjones1** [comment]
@bnmnetp, thanks! Fixed now.

**Pull request merged**
