### PR TITLE
Update: Use updated runestone init to re-create project.

### PR DESCRIPTION
**Pull request by bjones1**
This provides testing for https://github.com/RunestoneInteractive/RunestoneComponents/pull/764. It won't pass until that PR is merged.

### CODE REVIEW

**Comment by bjones1** [comment]
@bnmnetp, pinging.

**Comment by bnmnetp** [comment]
I thought I had accepted this, but it was similar branch name except with _ at the end...

**Comment by bjones1** [comment]
Hmm, I don't remember the history of that branch.

**Comment by bjones1** [comment]
Thanks!

**Pull request merged**
