### PR TITLE
Fix: Avoid invalid useinfo_id.

### PR DESCRIPTION
**Pull request by bjones1**
See https://github.com/RunestoneInteractive/RunestoneServer/issues/1093.

### CODE REVIEW

**Comment by bnmnetp** [comment]
Thanks @bjones1 -- Have you done grading on your installation with this PR?  We don't have a unit test that tests this path yet.  Want to write one 😁 ??

**Comment by bjones1** [comment]
Yes, this works on my install; without this, I get an exception.

Sigh -- I'd like to write tests, but lack the time during the semester to do this.

**Comment by bnmnetp** [comment]
I added a test

**Comment by bjones1** [comment]
Wow, way to go! That's helpful for me to add tests in the future...

**Pull request merged**
