### PR TITLE
Improve docker-tools for `build --single`

### PR DESCRIPTION
**Pull request by bjones1**
This implements ideas in #2048. Not much testing yet.

Fix: 
- auto-edit .env based on the build type.
- Links development-only files only in dev mode.

Docs: 
- Improve docs on .env.prototype

### CODE REVIEW

**Comment by bjones1** [comment]
@bnmnetp. OK works for me after testing. Test failures may be OK; the tests need to be re-run.

**Comment by bnmnetp** [comment]
tracking back a little further it is trying to run rsmanage but 
```
from rsmanage import cli
runestoneserver-runestone-1  | ImportError: cannot import name 'cli' from 'rsmanage'
```

**Comment by bnmnetp** [comment]
This is so weird, I can't even find anyplace in our code where we try to import cli from rsmanage.  Running the tests locally on my dev build and all is fine, so it seems to be something in the setup for the tests.

Any ideas???

**Comment by bjones1** [comment]
I'm guessing this is something new/broken with Poetry 1.4.0. In `rsmanage/setup.py`, we have:

```
    entry_points="""
        [console_scripts]
        rsmanage=rsmanage:cli
    """,
```
which is probably where the import of `cli` comes from. I'll test and see what happens.

**Comment by bjones1** [comment]
OK, testing a fix now...

**Comment by bnmnetp** [comment]
looks like it somehow lost the docker-tools test command...

**Comment by bnmnetp** [comment]
I'm seeing this message:
```
print("Note: this must be an initial install; additional commands missing.")
```

So something is going wrong with the import from `docker_tools_misc`

**Comment by bnmnetp** [comment]
my guess is that we now need to import `tests.ci_utils` not sure where this is coming from... poetry?? New setuptools?

**Comment by bnmnetp** [comment]
Some real backward incompatibility in poetry 1.4?  I see it was just released on the 2/27.  I had rebuilt locally a few days before. Looking at the changelog I didn't see see anything to indicate such major changes.

**Comment by bjones1** [comment]
That makes sense to me -- these fixes remove a lot of Poetry bug fix/workaround stuff, so I think it's a good step forward. Let's merge this, then you merge your 3.10 branch. Hopefully, that will get us back to all tests passing again!

**Comment by bjones1** [comment]
Do you want to merge this, or shall I?

**Comment by bnmnetp** [comment]
I'm on it.

**Pull request merged**
