### PR TITLE
Fix: Simplify the user-facing install process

### PR DESCRIPTION
**Pull request by bjones1**
This puts all the cloned repos in the `rsdocker/` subdirectory.

On OS X, it runs everything in a venv placed in `rsdocker/rsvenv`.

There are also lots of docs fixes and improvements.

### CODE REVIEW

**Comment by bjones1** [comment]
This is a larger PR, though most of the changes are in the docs. Hopefully, it's the last major fix to the Docker stuff for a while.

**Comment by bnmnetp** [comment]
Is this going to force me and others with working setups to change our directory structure?  I can't tell.

**Comment by bjones1** [comment]
No (mostly):
- After this PR, `runestone init` will clone repos in `rsdocker/` instead of the current directory.
- On OS X, it will now insist you run `docker-tools` from a virtual environment.

**Comment by bnmnetp** [comment]
Why will it insist on a VE for macOS?  Not linux?  Not Windows?  That seems like a weird distinction, further just a few weeks ago **nothing** worked if I tried to use a VE now I'm going to have to.

**Comment by bjones1** [comment]
OS X weirdness / a workaround. For some reason, on OS X running `pip install -e docker` to install `rsmanage` means that `rsmanage` isn't on the $PATH. It is for Windows and Linux. However, putting this in a venv on OS X makes these commands work (after activating the venv, which does the $PATH updates needed). I have no idea why OS X does this. The only thing in the venv is `click` and the `rsmanage` and `docker-tools` scripts. The venv is stored in a separate directory from the Docker Poetry environment and doesn't interact with it.

**Comment by bnmnetp** [comment]
I guess for me because I installed python using homebrew both docker-tools and rsmanage are installed in the /opt/homebrew/bin path which is added to one's path by homebrew.

I'm concerned about forcing someone to have a particular virtual environment as I have many different VE
s that I move between all of which allow me to run poetry, docker-tools, and rsmanage.

**Comment by bnmnetp** [comment]
I don't mean to make it more complicated, but I wonder if the confusion isn't from people on older macos using the delivered version of python.  In reality I think we should be telling people to install homebrew and then install a version of python with homebrew.  ?  homebrew is also a good way to install docker.  `brew install --cask docker` gives you the same docker desktop app as downloading a dmg.

**Comment by bnmnetp** [comment]
OK, I'm going to make a test user on my mac and see if I can figure out what is going on.

**Comment by bjones1** [comment]
Both David and Barb had new new M1 Macs. We never touched Python 2; I thought OS X didn't ship with Python 3 at all.

I fully agree with using homebrew to install Docker -- that's now in [this PR](https://github.com/RunestoneInteractive/RunestoneServer/pull/1977/files#diff-048861daf766efd50311c5aba6b2586ccfe82698d3dd9470786b0826004a2b6dR45).

Thanks for Mac help. At some point, I'll rent another macincloud, but I have so little need for that other than the occasional Docker stuff.

**Comment by bjones1** [comment]
OK, I finally integrated these updates. I didn't realize this wasn't a draft PR and force-pushed a rebase and some fixes.

**Comment by bjones1** [comment]
OK, finally wrapping this up. Ready for (re-)review.

**Pull request merged**
