### PR TITLE
Port: Python 3 updates.

### PR DESCRIPTION
**Pull request by bjones1**
This PR contains many changes to enable the Runestone server to run under Python 2 or Python 3. Note that some of these changes require the latest version of web2py when running under Python 3.

### CODE REVIEW

**Comment by bnmnetp** [comment]
@bjones1 -- was looking at this today for a bit.

Do we need the latest dev version ? I upgraded to `Version 2.18.4-stable+timestamp.2019.03.13.05.27.54` . but maybe you are using an even later version from the dev tree??

In trying under 3.7.1 I ran into an easy problem:  need to change `request.cookies.has_key('ipuser')` to `'ipuser' in request.cookies` but also a hard problem in that `import rs_grading` results in a module not found, along with errors about oauth2...  Haven't figured that one out yet.

**Comment by bjones1** [comment]
Oops, my apologies. My cherry-pick to produce this PR failed massively. I've updated it and verified that it passes most tests (except test_assignments, which needs to debug / porting / help) while also passing all Python 2 tests.

I'm testing under web2py 2.18.4 as well.

**Comment by bjones1** [comment]
I'll update this in a bit with fixed conflicts.

**Comment by bnmnetp** [comment]
Cool.  I'll update my test branch later today then.

**Comment by bjones1** [comment]
OK, fixed now.

**Comment by bjones1** [comment]
@bnmnetp, this should be merged into master, not a separate port branch. This port should work identically on Python 2 and Python 3, since it uses `six` where necessary. This also makes maintenance easier -- trying to keep two branches up to date is more work.

**Comment by bnmnetp** [comment]
I’m getting validation errors when I run the tests today

**Comment by bjones1** [comment]
On py2 or py3? My py2 tests all pass. I only have py3 failures (which needs help from people who know that code). But, this shouldn't block a merge, it's just that py3 isn't fully ready yet.

**Comment by bnmnetp** [comment]
It’s python2.  I’m not at my computer at the moment, but it has to do with a meta tag and setting an attribute to make sure that Edge is used if I remove ‘,chrome=1’ from that attribute it passes the validation

**Comment by bjones1** [comment]
I just reran tests on `platform win32 -- Python 2.7.15, pytest-4.3.1, py-1.6.0, pluggy-0.7.1 -- F:\Downloads\Python27-32\python.exe`, using web2py Version 2.18.4-stable+timestamp.2019.03.13.05.27.54, and everything passes for me. The [travis build](https://travis-ci.org/RunestoneInteractive/RunestoneServer/builds/514982261?utm_source=github_status&utm_medium=notification) also passed. Perhaps there's something confused in your environment? If you pass me a more specific error message/trackback, I can take a look.

**Comment by bnmnetp** [comment]
Here's the test that fails:
`applications/runestone/tests/test_server.py::test_1[default/user/login-False-Login-1] ERROR `

```
============================= ERRORS =============================
___ ERROR at setup of test_1[default/user/login-False-Login-1] ___

runestone_db_tools = <applications.runestone.tests.test_server._RunestoneDbTools object at 0x10da54f50>
test_user = <function <lambda> at 0x10c812e60>

    @pytest.fixture
    def test_user_1(runestone_db_tools, test_user):
        with runestone_db_tools.create_course('test_course_1'), \
>           test_user('test_user_1', 'password_1', 'test_course_1') as test_user_1:



self = <applications.runestone.tests.test_server._TestClient object at 0x10caf71d0>
url = 'default/user/logout', expected_string = 'Logged out'
expected_errors = None, expected_status = 200, kwargs = {}
@py_assert1 = False
@py_assert3 = '\n<!DOCTYPE html>\n<html lang="en">\n    <head>\n        <title>\n            Runestone Interactive\n        </title>...[0]; s.parentNode.insertBefore(ga, s);\n                })();\n            </script>\n        \n    </body>\n</html>\n'
@py_format5 = '\'Logged out\' in \'\n<!DOCTYPE html>\n<html lang="en">\n    <head>\n        <title>\n            Runestone Interacti...      \n    </body>\n</html>\n\' = <applications.runestone.tests.test_server._TestClient object at 0x10caf71d0>.text
}'

    def validate(self,
        # The relative URL to validate.
        url,
        # An optional string that, if provided, must be in the text returned by the server. If this is a list of strings, at least one of the provided strings but be in the text returned by the server.
        expected_string='',
        # The number of validation errors expected. If None, no validation is performed.
        expected_errors=None,
        # The expected status code from the request.
        expected_status=200,
        # All additional keyword arguments are passed to the ``post`` method.
        **kwargs):
    
        try:
            try:
                self.post(url, **kwargs)
            except HTTPError as e:
                # If this was the expected result, return.
                if e.code == expected_status:
                    # Since this is an error of some type, these paramets must be empty, since they can't be checked.
                    assert not expected_string
                    assert not expected_errors
                    return ''
                else:
                    raise
            assert self.status == expected_status
            if expected_string:
                if isinstance(expected_string, str):
>                   assert expected_string in self.text
E                   assert 'Logged out' in '\n<!DOCTYPE html>\n<html lang="en">\n    <head>\n        <title>\n            Runestone Interactive\n        </title>...[0]; s.parentNode.insertBefore(ga, s);\n                })();\n            </script>\n        \n    </body>\n</html>\n'
E                    +  where '\n<!DOCTYPE html>\n<html lang="en">\n    <head>\n        <title>\n            Runestone Interactive\n        </title>...[0]; s.parentNode.insertBefore(ga, s);\n                })();\n            </script>\n        \n    </body>\n</html>\n' = <applications.runestone.tests.test_server._TestClient object at 0x10caf71d0>.text

applications/runestone/tests/test_server.py:285: AssertionError
--------------------- Captured stdout setup ----------------------
Validation failure saved to default-user-logout.html.

```
When I feed the saved page to validator.w3.org I complains about this line:
```
<meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
```
but if I remove the `,crome=1 ` part then it passes.

**Comment by bnmnetp** [comment]
But maybe I"m not understanding the output from the tests.

**Comment by bjones1** [comment]
Since `expected_errors = None`, this call to validate isn't using the W3C validator. Since `expected_string = 'Logged out'`, it's expecting to see that message in the HTML pulled from the specified page (`url = 'default/user/logout'`). Would you mind opening the file `default-user-logout.html` (saved in the web2py directory) to see what's going on, and perhaps posting it here? That's the HTML produced by hitting the specified web2py endpoint.

**Comment by bnmnetp** [comment]
```

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            Runestone Interactive
        </title>
        <meta charset='utf-8'>
        <meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
        <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1'>
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="description" content="Learning Python should be fun and easy.  We provide an interactive Python textbook that helps you learn to program in Python right in your browser.">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="/runestone/static/bootstrap-sphinx.css" />
        <link rel="stylesheet" type="text/css" href="/runestone/static/runestone-custom-sphinx-bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="/runestone/static/css/dd.css" />
        <link rel="shortcut icon"
            href="/runestone/static/favicon.ico" type="image/ico" />
        <script src="/runestone/static/js/jquery-1.10.2.min.js"></script>
        <script src="/runestone/static/js/jquery-fix.js"></script>
        <script src="/runestone/static/js/web2py.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="/runestone/static/bootstrap-sphinx.js"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <style type="text/css">
        .rscontainer {
            padding-left: 20px;
            padding-right:20px;
            padding-top: 20px;
        }
    </style>

        <script type="text/javascript">
            var eBookConfig = {};
            var portPart = '';
            eBookConfig.host = "";
            eBookConfig.app = eBookConfig.host+'/runestone';
            eBookConfig.ajaxURL = eBookConfig.app+'/ajax/';
            eBookConfig.logLevel = 10;
            eBookConfig.loginRequired = true;
        </script>
    </head>
    <body>

        <!-- needed for Facebook button -->

        <div id="fb-root"></div>
        <script>
            (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
            fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>

        <!-- Begin navbar -->
        <div id="navbar" class="navbar navbar-default navbar-fixed-top" role="navigation">

            <div class="container">
                <div class="navbar-header">
                    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
                    <button type='button' class='navbar-toggle' data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <div>

                            <a class="brand-logo" style='background: transparent url("/runestone/static/images/logo_small.png") no-repeat 0px 0px;' href="/runestone/default/user/login">&nbsp; </a>

                    </div>
                </div>
                <div class="navbar-collapse collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="divider-vertical"></li>
                        <!-- social media dropdown -->


                        <li class="dropdown">
                            <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                            <i class="glyphicon glyphicon-share" style="opacity: 0.9"></i>
                            </a>
                            <ul class="dropdown-menu social-menu">
                                <li>
                                    <div>
                                        <b>Runestone in social media:</b>
                                    </div>
                                    <a href="https://twitter.com/iRunestone" class="twitter-follow-button" data-show-count="true">Follow @iRunestone</a><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                                    <div class="fb-like" data-href="https://www.facebook.com/RunestoneInteractive" data-send="false" data-layout="button_count" data-width="300" data-show-faces="false" data-font="arial"></div>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <div>
                                        <b>Help support us:</b>
                                    </div>
                                    <div>
                                        <a href="/runestone/default/donate"> <img src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" alt="PayPal - The safer, easier way to pay online!"></a>
                                    </div>
                                </li>
                            </ul>
                        </li>

                        <!-- end social media dropdown -->
                        <li class="divider-vertical"></li>
                        <!-- user account dropdown -->
                        <li class="dropdown">
                            <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                                <i class="glyphicon glyphicon-user" style="opacity:0.9;"></i>
                            </a>
                            <ul class="dropdown-menu user-menu">

                                    <li><span class='loggedinuser'>Not logged in</span></li>


                                <!---
                                    <li class="divider"></li>
                                    <li><a href='/runestone/mygroup/schedule'>Group Schedule</a></li>
                                    <li><a href='/runestone/mygroup/newschedule'>Schedule New Chapter</a></li>
                                    <li><a href='/runestone/mygroup/manageGroup'>Manage Group</a></li> -->

                                <li class="divider"></li>
                                <li><a href='/runestone/admin/index'>Instructor's Page</a></li>
                                <li class="divider"></li>



                                    <li><a href='/runestone/default/user/register'>Register</a></li>
                                    <li class='loginout'><a href='/runestone/default/user/login'>Login</a></li>


                            </ul>
                        </li>
                        <!-- end user account dropdown -->
                        <li class="divider-vertical"></li>

                        <!-- help menu dropdown -->
                        <li class="dropdown">
                            <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                            <i class="glyphicon glyphicon-question-sign" style="opacity:0.9;"></i>
                            </a>
                            <ul class="dropdown-menu user-menu">
                                <li><a href='https://runestone.academy/runestone/static/instructorguide/index.html'>Help for Instructors</a></li>
                                <li class="divider"></li>
                                <li><a href='http://www.runestoneinteractive.org/pages/about.html'>About Runestone</a></li>
                                <li><a href='/runestone/default/reportabug'>Report A Problem</a></li>
                            </ul>
                        </li>
                        <li class="divider-vertical"></li>

                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="divider-vertical"></li>

                            <!-- open library dropdown -->
                            <li class="dropdown">
                                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Book Links<b class="caret"></b></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a href="/runestone/static/fopp/index.html">Foundations of Python Programming</a></li>
                                    <li><a href="/runestone/static/thinkcspy/index.html">How To Think Like a Computer Scientist: Interactive edition</a></li>
                                    <li><a href="/runestone/static/pythonds/index.html">Problem Solving With Algorithms and Data Structures using Python</a></li>
                                    <li><a href="/runestone/static/cppds/index.html">Problem Solving With Algorithms and Data Structures using C++</a></li>
                                    <li><a href="/runestone/static/java4python/index.html">Java For Python Programmers</a></li>
                                    <li><a href="/runestone/static/JavaReview/index.html">Java Review for AP CS A Exam</a></li>
                                    <li><a href="/runestone/static/StudentCSP/index.html">CS Principles: Big Ideas inProgramming</a></li>
                                    <li><a href="/runestone/static/learnwebgl2/index.html">Learn Computer Graphics using WebGL <strong>New</strong></a></li>
                                    <li><a href="/runestone/static/JS4Python/index.html">Javascript for Python Programmers <strong>Beta</strong></a></li>
                                    <li><a href="/runestone/static/cpp4python/index.html">C++ for Python Programmers <strong>New</strong></a></li>
                                    <li><a href="/runestone/static/httlads/index.html">How to Think like a Data Scientist <strong>Beta</strong></a></li>
                                    <li><a href="/runestone/static/overview/overview.html">Runestone Directives</a></li>
                                    <li><a href="http://everydaypython.org">Everyday Python Blog</a></li>
                                    <li><a href="/runestone/static/instructorguide/index.html">Runestone Instructor Guide</a></li>
                                </ul>
                            </li>

                        <li class="divider-vertical"></li>




                        <li class="divider-vertical"></li>
                    </ul>

                        <a href="/runestone/default/user/register" class="btn btn-primary navbar-btn" ><span class="glyphicon glyphicon-user"></span>Sign Up</a>

                </div>
            </div>
        </div>

        <!-- End navbar -->

        <!-- begin body content -->
        <div class="container">







<div class="container rscontainer">



        <div class="row">

            <!-- Carousel
            ================================================== -->
            <link href="/runestone/static/css/carousel.css" rel="stylesheet">
            <div class="carousel slide col-md-8" data-ride="carousel" id="myCarousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                    <li data-target="#myCarousel" data-slide-to="3"></li>
                    <li data-target="#myCarousel" data-slide-to="4"></li>
                    <li data-target="#myCarousel" data-slide-to="5"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <div class="container">
                            <div class="carousel-caption">
                                <h3>Welcome to Runestone Academy</h3>
                                <p>We host a growing number of open source, interactive textbooks, written by award winning authors. Used by hundreds of schools</p>
                                <p><a class="btn btn-lg btn-primary" href="http://runestoneinteractive.org/pages/library.html" role="button">See the List</a> <a class="btn btn-lg btn-primary" href="https://runestone.academy/runestone/static/overview/overview.html" role="button">Take a Tour</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="container">
                            <div class="carousel-caption">
                                <h3>How to Think Like a Computer Scientist: Interactive Edition</h3>
                                <p>Based on the original open source book. Learn Python, try examples, answer questions, interactively, right in the book!</p>
                                <p><a class="btn btn-lg btn-primary" href="https://runestone.academy/runestone/static/thinkcspy/index.html" role="button">Try it Now</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="container">
                            <div class="carousel-caption">
                                <h2>New Instructors</h2>
                                <p>Here is a Video that will help you get started. Or, take a tour of the unique interactive features of our books!</p>
                                <p><a class="btn btn-lg btn-primary" href="https://youtu.be/IGg_SUWEnGU" role="button">Watch Video</a> <a class="btn btn-lg btn-primary" href="https://runestone.academy/runestone/static/instructorguide/index.html" role="button">Instructors Guide</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="container">
                            <div class="carousel-caption">
                                <h3>Algorithms and Data Structures using Python</h3>
                                <p>Written by Brad Miller and David Ranum, this is a free and open source version of the book published by Franklin Beedle.</p>
                                <p><a class="btn btn-lg btn-primary" href="https://runestone.academy/runestone/static/pythonds/index.html" role="button">Learn more</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="container">
                            <div class="carousel-caption">
                                <h3>CS Principles -- Big Ideas in Programming</h3>
                                <p>By Mark Guzdial, Barbara Ericson, and Briana Morrison This book introduces important concepts for the new AP CS Principles course.</p>
                                <p><a class="btn btn-lg btn-primary" href="https://runestone.academy/runestone/static/StudentCSP/index.html" role="button">Learn more</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <div class="container">
                            <div class="carousel-caption">
                                <h3>Java Review for the AP CS A Exam</h3>
                                <p>Not just for Python. This great resource, written by Barbara Ericson, is loaded with review questions and clear explanations.</p>
                                <p><a class="btn btn-lg btn-primary" href="https://runestone.academy/runestone/static/JavaReview/index.html" role="button">Get Started</a></p>
                            </div>
                        </div>
                    </div>
                </div><a class="left carousel-control" data-slide="prev" href="#myCarousel"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" data-slide="next" href="#myCarousel"><span class="glyphicon glyphicon-chevron-right"></span></a>
            </div><!-- /.carousel -->
            <h4 class="col-md-4">Login</h4>


            <!--  LOGIN -->


                <div id="web2py_user_form" class="col-md-4">
                    <form class="form-horizontal" method="post">

                            <div class="form-group">
                                <div class="col-sm-offset-2">
                                    <label for="auth_user_username" class="control-label">Username</label>
                                    <input type="text" class="form-control col-xs-4" id="auth_user_username" name="username"
                                           placeholder="Enter username" autofocus>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2">
                                    <label for="auth_user_password" class="control-label">Password</label>
                                    <div>
                                        <input type="password" class="form-control" id="auth_user_password" name="password"
                                            placeholder="Enter password">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2">
                                    <div class="checkbox">
                                        <label>
                                            <input id="auth_user_remember_me" name="remember_me" type="checkbox"> Remember me
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-4">
                                    <button type="submit" class="btn btn-default">Login</button>
                                </div>
                            </div>

                    <div style="display:none;"><input name="_next" type="hidden" value="/runestone/default/index" /><input name="_formkey" type="hidden" value="e1647107-61c9-4a2a-a0c2-c7cb35e9972c" /><input name="_formname" type="hidden" value="login" /></div></form>
                    <!-- Must use this to get all the good defaults for the form -->
                    <div id='auth-actions' class="col-md-4">

                            <a class="btn btn-sm btn-primary" href="/runestone/default/user/request_reset_password"
                                role="button">Lost Password</a>
                            <a class="btn btn-sm btn-primary" href="/runestone/default/user/retrieve_username"
                                role="button">email my username</a>

                    </div>
                </div>





        </div>
      <!-- end of always show the carousel EXCEPT for registration -->

    <div class="content row">
        <!-- REGISTRATION -->
         <!-- end register page -->


            <div class="row">
                <div class='col-md-6'>
                    <h2>About Runestone</h2>
                    <p>The mission of Runestone Interactive is to democratize textbooks for the 21st century.  Textbook prices are too high, and paper textbooks are too old fashioned.  We are changing that.</p>
                    <ul>
                        <li>Freely available open source books</li>
                        <li>Easy to use uthoring tools to create Runestone books</li>
                        <li>Hosting services for your course - See our <a href="https://runestone.academy/runestone/static/instructorguide/index.html">Instructor Guide</a></li>
                    </ul>
                    <p>To learn more about this project, <a href="https://runestone.academy/runestone/static/overview/overview.html">see this overview</a>. For more information about the whole <b>Runestone Interactive</b> community and project, including how to contribute, please <a href="http://runestoneinteractive.org">click here</a>!</p>
                </div>
                <div class="col-md-6">
                    <h2>Support Us</h2>
                    <p>This project is Open Source, but it does take time and resources.
                        Especially as our popularity has grown we have server costs. We
                        were also able to make great progress during the Summer of 2013
                        thanks to a generous grant from ACM-SIGCSE that supported one of our
                        undergraduate students. It would be great if we could have a student
                        working on this all the time.</p>
                    <p>If these books have helped you, if you liked them,
                        please consider making a small donation.</p>
                    <a href="/runestone/default/donate"><img src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" alt="PayPal - The safer, easier way to pay online!"></a>
                </div>
            </div>


            <div class="col-md-6">
                <h2>Your Privacy</h2>
                <p>The books provided on Runestone Academy are free and open source. They are for educational purposes. As part
                    of our educational mission we do collect usage data to help us better understand how you learn and how you
                    use our
                    books. In exchange, we may use this data to make decisions about revisions to the content, and we may use
                    this data to publish
                    academic papers. We would never publish anything that revealed your identity. We may share this data with
                    fellow
                    educational researchers, but rest assured that all personally identifying information will be anonymized
                    before we do.
                    If you have questions about this please feel free to <a
                            href="mailto:runestoneinteractive@gmail.com">contact</a> us.</p>
            </div>

    </div>
</div>

<script language="javascript" type="text/javascript">
    var cur_course = $('#auth_user_course_id').val();
    if (cur_course == '') {
        $('#auth_user_course_id').val('thinkcspy, pythonds, pip or other')
    }
    $("#auth_user_course_id").on("click", function () {
       $(this).select();
    });
</script>

        </div>
        <!-- end body content -->

        <!-- begin footer -->
        <footer class="footer" style="margin-top:20px;">
            <div class="container">
                <p class="pull-right">

                        <span class='loggedinuser'>Not logged in</span> | <a href="#">Back to top</a>

                </p>
                <p>
                    &copy; Copyright 2018 Runestone Interactive LLC

                        &emsp; ● <a href="/runestone/default/privacy">Privacy Policy</a> &emsp; ●  <a href="/runestone/default/terms">Terms of Service</a>

                </p>
            </div>
        </footer>
        <!-- end footer -->



        <script type="text/javascript" id="cookieinfo"
            src="//cookieinfoscript.com/js/cookieinfo.min.js"
            data-bg="#645862"
            data-fg="#FFFFFF"
            data-link="#F1D600"
            data-cookie="CookieInfoScript"
            data-message="By continuing to visit this site you agree to our use of cookies and our privacy policy."
            data-moreinfo="https://runestone.academy/runestone/default/privacy"
            data-text-align="left"
            data-close-text="Got it!"></script>

        <script type='text/javascript'>
            // do some styling of the web2py login and registration form
            // this is done here because web2py doesn't have an easy way
            // to add class to the auth form. We don't want to duplicate the
            // styles from .form-control into our custom CSS.
            var el = $("#web2py_user_form");
            el.find("input[type='text']").addClass('form-control');
            el.find("input[type='password']").addClass('form-control');
        </script>

            <script type="text/javascript">
                var _gaq = _gaq || [];
                _gaq.push(['_setAccount', 'UA-32029811-1']);
                _gaq.push(['_trackPageview']);

                (function() {
                  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
                })();
            </script>

    </body>
</html>
```

**Comment by bjones1** [comment]
Strange -- this is the standard login page, from what I can tell. Here's what I see when I logout from my site:

image

There should be a `<div class="flash" style="display: block;">Logged out</div>` in the resulting HTML. I'm not sure why this isn't happening. Again, this is fine on my PC and Travis. Do you have time to do a Hangout so I can better understand what's wrong?

**Comment by bnmnetp** [comment]
Here is the complete output from running the test

[test_output.txt](https://github.com/RunestoneInteractive/RunestoneServer/files/3040361/test_output.txt)

**Comment by bnmnetp** [comment]
I'm in the middle of a longish hangout with my Google team.  2 hours left.

**Comment by bjones1** [comment]
OK. I'll see if I can come up with any other ideas.

**Comment by bjones1** [comment]
I wonder if your environment is broken in some way? Would you mind checking out the parent commit (9cb6818549c276edbc4f267f806ccc4f54286d12) and running these tests there first? If these pass...

The error occurs on the setup of the first test. The same setup runs for most of the remaining tests. So, there's some start-up problem. I've seen problems where web2py took too long to start (to fix, edit the delay on `test_server.py` line 137), but if web2py isn't started, you'd get no response, not an incorrect response. Therefore, there's something that causes your server not to display the flash message the first time only, then run fine after that. I'm definitely confused. Random flailing ideas:

1. Comment out line 580. Does the failure still occur?
2. Are there any other instances (perhaps a non-killed process) of the web2py server that's running and causing confusion?
3. Perhaps increasing the delay on line 137 (but I don't see why that would help).
4. Something in running in a virtualenv? I don't use it, not do the Travis tests.

**Comment by bnmnetp** [comment]
Hmm, master branch runs without error.

I'm going to delete the branch for this PR and start over.

**Comment by bjones1** [comment]
OK, sounds good.

**Comment by bnmnetp** [comment]
Strange, deleting the week old branch, which I pulled updates to, and replacing it with a brand new branch from master now the tests all pass. !!

**Comment by bjones1** [comment]
Great! That's a big sigh of relief from me. I had no idea what was wrong...

**Comment by bjones1** [comment]
Thanks!

**Pull request merged**
